services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/Neon17/blood_bank_backend
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - fromGroup: laravel-env

envVarGroups:
  - name: laravel-env
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'true'
      - key: APP_KEY
        value: 'base64:ELC7jEBTZzHiiEXPCYlLvj438RLW8l6JufuM0FBTBSw='
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1mesn15pdvs73cu66fg-a.singapore-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: blood_bank_backend
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: vjQw2EPdyKMvFfsFG9wo8FUcjHnfRUIK
